chore(WixPatternsTemplate): add comments to the template
wix/cli-app-templates pull request #37
Opened 2024-09-05 12:43 UTC by nofar9792

https://jira.wixpress.com/browse/CAIRO-1996

2024-09-08 09:13 UTC, sam-prais requested changes

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +// Defining the types for filters used in the table
```suggestion
// Define filter types for the table.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +// Defining the type for supported query fields
```suggestion
// Define the type for supported query fields.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +// Mapping product types to display names
```suggestion
// Map product types to display names.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +    limit: 20, // Number of items per page
```suggestion
    limit: 20, // Max items per page
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +    fetchData: (query) => { // Function to fetch product data based on the given query
```suggestion
    // Define a function to fetch product data based on the query provided.
    fetchData: (query) => {
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +      // Setting initial query parameters
```suggestion
      // Set the initial query parameters.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +      // If search term is provided, filter products by name
```suggestion
      // If a search string is provided, filter the products by name.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +      // If filters are applied, add them to the query
```suggestion
      // If filters are provided, add them to the query.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +      // If sorting is applied, add sorting conditions to the query
```suggestion
      // If sorting is provided, add them to the query.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +      // Execute the query and return the items and total count
```suggestion
      // Execute the query, and then return the items and total count.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +  // Optimistic actions to handle changes before server confirmation
```suggestion
  // Set optimistic actions for changes to the product data.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +            const disabled = selectedValues.length > 20; // Disable delete if more than 20 items selected
```suggestion
            const disabled = selectedValues.length > 20; // If more than 20 items are selected, disable delete.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +              // Custom toolbar for bulk actions
```suggestion
              // Add a Custom Toolbar for bulk actions.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +          customColumns={<CustomColumns />} // Enable custom columns for the table
```suggestion
          // Enable Custom Columns for the table.
          customColumns={<CustomColumns />}
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +              // Use predefined delete action
```suggestion
              // Use the predefined deleteSecondaryAction function.
```

2024-09-08 09:13 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +// Wrapping the Products component with providers
```suggestion
// Wrap the Products component with withProviders.
```

2024-09-15 05:44 UTC, sam-prais approved these changes

2024-09-15 05:44 UTC, sam-prais commented on custom-products-catalog/template/src/dashboard/pages/page.tsx
> +    // Define a function to fetch product data based on the query provided.
```suggestion

    // Define a function to fetch product data based on the query provided.
```

2024-09-15 07:17 UTC, matveyok approved these changes

2024-09-15 07:18 UTC, merged